In [1]:
import pandas as pd

In [23]:
#map number to id
idmap = pd.read_csv('../output/260804_allgh18_header_map.txt')
parts = idmap['header'].str.split('|', n=1, expand=True)
idmap['Entry'] = parts[0]
idmap

          id           header       Entry
0          0  A0A010YG22|1of1  A0A010YG22
1          1  A0A011PM39|1of2  A0A011PM39
2          2  A0A011PM39|2of2  A0A011PM39
3          3  A0A011PXQ4|1of2  A0A011PXQ4
4          4  A0A011PXQ4|2of2  A0A011PXQ4
...      ...              ...         ...
41899  41899      X6Q4Q0|2of2      X6Q4Q0
41900  41900      X8GPF2|1of1      X8GPF2
41901  41901      X8HE75|1of1      X8HE75
41902  41902      Z9JN00|1of1      Z9JN00
41903  41903      Z9JR83|1of1      Z9JR83

[41904 rows x 3 columns]

In [29]:
clustermap = pd.read_csv(f'../output/mmseqs_clustering/260804_allgh18_mmseqs_clusters_473.0.csv')
clust293 = idmap.merge(clustermap, on='id', how='left')
clust293.to_csv('260804_allgh18_mmseqs_clusters_473.csv', index=False)

In [ ]:
level = '293'
cluster = 4
txtfile_name = f'../output/unique_IDs_IPR001223_level{level}_cluster{cluster}.txt'

clustermap = pd.read_csv(f'../output/mmseqs_clustering/mmseqs_clustering_250711/IPR001223_FL_mmseqs_clusters_{level}.0.csv')
clustermap = clustermap[clustermap['cluster'] == cluster]
clustermap = clustermap.merge(idmap, on='id', how='left')
clustermap #= clustermap[['Entry', 'id']]

unique_entries = clustermap['Entry'].unique()
with open(f'{txtfile_name}', 'w') as f:
    for entry in unique_entries:
        f.write(f"{entry}\n")

In [13]:
cluster162 = pd.read_csv('id_header_clustersat162.csv')
annot = pd.read_csv('annot_table_IPR001223_bact_arch_jackseq_annot_HMMseqs_and_NOhmmexplodeddomains_ANNOT_pfamscan.csv')

cluster162

/var/folders/k3/7_cndd213s1_cf9yqdgvytf80000gn/T/ipykernel_4769/1816008407.py:2: DtypeWarning: Columns (0: Domain [CC]) have mixed types. Specify dtype option on import or set low_memory=False.
  annot = pd.read_csv('annot_table_IPR001223_bact_arch_jackseq_annot_HMMseqs_and_NOhmmexplodeddomains_ANNOT_pfamscan.csv')

,Unnamed: 0,id,cluster,header,Uniprot_Accessions,fastaID
0,0,32771,0,A0AAU2JM17|1of1,A0AAU2JM17,A0AAU2JM17|1of1
1,1,32772,0,A0AAU2JQ17|1of1,A0AAU2JQ17,A0AAU2JQ17|1of1
2,2,6,0,A0A014M4I2|1of1,A0A014M4I2,A0A014M4I2|1of1
3,3,32775,0,A0AAU2JXC5|1of1,A0AAU2JXC5,A0AAU2JXC5|1of1
4,4,32776,0,A0AAU2JZH4|1of1,A0AAU2JZH4,A0AAU2JZH4|1of1
...,...,...,...,...,...,...
38199,38199,29248,280,A0A9D2CDH2|1of1,A0A9D2CDH2,A0A9D2CDH2|1of1
38200,38200,29429,281,A0A9D8RIT8|1of1,A0A9D8RIT8,A0A9D8RIT8|1of1
38201,38201,29543,282,A0A9E2MJ66|1of1,A0A9E2MJ66,A0A9E2MJ66|1of1
38202,38202,32272,283,A0AAU0LBN9|1of1,A0AAU0LBN9,A0AAU0LBN9|1of1
38203,38203,35707,284,D3P6G5|1of1,D3P6G5,D3P6G5|1of1

In [9]:
annot#order annot by domain num

,Entry,Domain_number,Start,End,Score,Domain_sequence,Total_domains,Reviewed,Entry Name,Protein names,...,Entry|domains,kingdom,phylum,class,order,family,genus,species,Entry|domains|HMM|org,Pfamscan
0,A0A1H5YSH1,1,484,809,3.900000e-81,VIAYVPGWKNWSASNPIDAAKLTHINYAFTHVKDNKIVALPGQNDD...,3,unreviewed,A0A1H5YSH1_9BACL,chitinase (EC 3.2.1.14),...,A0A1H5YSH1|1of3,Bacillati,Bacillota,Bacilli,Bacillales,Paenibacillaceae,Paenibacillus,Paenibacillus_sp._UNC499MF,A0A1H5YSH1|1of3|HMM|Paenibacillus_sp._UNC499MF,PF00395 PF00395 PF00395 PF00704 PF00704 PF00704
1,A0A1H5YSH1,2,915,1241,1.200000e-78,VIAYVAGWKNWSDVKPVDAAKLTHINYAFTHVKDNKIVPIEGQNDE...,3,unreviewed,A0A1H5YSH1_9BACL,chitinase (EC 3.2.1.14),...,A0A1H5YSH1|2of3,Bacillati,Bacillota,Bacilli,Bacillales,Paenibacillaceae,Paenibacillus,Paenibacillus_sp._UNC499MF,A0A1H5YSH1|2of3|HMM|Paenibacillus_sp._UNC499MF,PF00395 PF00395 PF00395 PF00704 PF00704 PF00704
2,A0A1H5YSH1,3,1347,1670,2.200000e-78,VIAYIAGWEDWSVTNSVYANKLTHLNYSFTLVKDNKIITRPEQKDD...,3,unreviewed,A0A1H5YSH1_9BACL,chitinase (EC 3.2.1.14),...,A0A1H5YSH1|3of3,Bacillati,Bacillota,Bacilli,Bacillales,Paenibacillaceae,Paenibacillus,Paenibacillus_sp._UNC499MF,A0A1H5YSH1|3of3|HMM|Paenibacillus_sp._UNC499MF,PF00395 PF00395 PF00395 PF00704 PF00704 PF00704
3,F5LPK1,1,468,793,1.800000e-80,VIAYVPGWKNWSASNPIDAAKLTHINYAFTHVKDNKIVSLPAQNDD...,3,unreviewed,F5LPK1_9BACL,chitinase (EC 3.2.1.14),...,F5LPK1|1of3,Bacillati,Bacillota,Bacilli,Bacillales,Paenibacillaceae,Paenibacillus,Paenibacillus_sp._HGF7,F5LPK1|1of3|HMM|Paenibacillus_sp._HGF7,PF00395 PF00395 PF00395 PF00704 PF00704 PF00704
4,F5LPK1,2,899,1225,2.200000e-78,VIAYVGGWKNWSEAKPVDASKLTHINYAFTHVKDNKIVPIEVQNDD...,3,unreviewed,F5LPK1_9BACL,chitinase (EC 3.2.1.14),...,F5LPK1|2of3,Bacillati,Bacillota,Bacilli,Bacillales,Paenibacillaceae,Paenibacillus,Paenibacillus_sp._HGF7,F5LPK1|2of3|HMM|Paenibacillus_sp._HGF7,PF00395 PF00395 PF00395 PF00704 PF00704 PF00704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40308,A0A2Z2NGA0,1,653,924,NaN,HFFAPYIDMTLSVHKPLTEYAQLTGTKYFTLAFIIYSSAYGPSWGG...,1,unreviewed,A0A2Z2NGA0_9EURY,Chitinase,...,A0A2Z2NGA0|1of1,Methanobacteriati,Methanobacteriota,Thermococci,Thermococcales,Thermococcaceae,Thermococcus,Thermococcus_chitonophagus,A0A2Z2NGA0|1of1|noHMM|Thermococcus_chitonophagus,PF00553
40309,A0A3N6MAZ1,1,173,454,NaN,GIYSPYQGTWYDVVDGTLGRDTDRVIVAFVGDPHRNGEISPAWLAN...,1,unreviewed,A0A3N6MAZ1_NATCH,PKD domain-containing protein,...,A0A3N6MAZ1|1of1,Methanobacteriati,Methanobacteriota,Halobacteria,Halobacteriales,Natrialbaceae,Natrarchaeobius,Natrarchaeobius_chitinivorans,A0A3N6MAZ1|1of1|noHMM|Natrarchaeobius_chitiniv...,PF02839 PF18911
40310,A0A8T3UZL4,1,370,628,NaN,CVNNGYWLFGYNMKNVNLDKLAKTSTKHIFLNFAALEKHGKSAVET...,1,unreviewed,A0A8T3UZL4_9EURY,GH18 domain-containing protein,...,A0A8T3UZL4|1of1,Methanobacteriati,Methanobacteriota,Methanobacteria,Methanobacteriales,Methanobacteriaceae,Methanobrevibacter,Methanobrevibacter_sp,A0A8T3UZL4|1of1|noHMM|Methanobrevibacter_sp,PF13200
40311,M0IGJ5,1,180,480,NaN,SIFAPYVDMMLEDQLSLADNVEAAGTKYFTLAFVLADDNGEPAWAG...,1,unreviewed,M0IGJ5_9EURY,Chitinase / lysozyme,...,M0IGJ5|1of1,Methanobacteriati,Methanobacteriota,Halobacteria,Halobacteriales,Haloferacaceae,Haloferax,Haloferax_mucosum_ATCC_BAA-1512,M0IGJ5|1of1|noHMM|Haloferax_mucosum_ATCC_BAA-1512,PF02839 PF18911
40312,R4W8T7,1,427,719,NaN,SGTSTFAPYNHMTTQPGTSLVDHYNQASNDAFTLAFVLSDGNGNAA...,1,unreviewed,R4W8T7_9EURY,PKD domain-containing protein,...,R4W8T7|1of1,Methanobacteriati,Methanobacteriota,Halobacteria,Halobacteriales,Natronoarchaeaceae,Salinarchaeum,Salinarchaeum_sp._Harcht-Bsk1,R4W8T7|1of1|noHMM|Salinarchaeum_sp._Harcht-Bsk1,PF18911 PF18911 PF02839 PF18911

In [21]:
#only take columns Entry and Domain_number from annot
annot = annot[['Entry', 'Total_domains']]
annot_cluster162 = annot.merge(cluster162, left_on='Entry', right_on = 'Uniprot_Accessions',how='left')
annot_cluster162 = annot_cluster162.drop_duplicates(subset=['Entry'], keep='first')
annot_cluster162

,Entry,Total_domains,Unnamed: 0,id,cluster,header,Uniprot_Accessions,fastaID
0,A0A1H5YSH1,3,3665.0,5015.0,0.0,A0A1H5YSH1|1of3,A0A1H5YSH1,A0A1H5YSH1|1of3
9,F5LPK1,3,2492.0,36097.0,0.0,F5LPK1|1of3,F5LPK1,F5LPK1|1of3
18,A0A410WPN7,3,7427.0,14536.0,0.0,A0A410WPN7|1of3,A0A410WPN7,A0A410WPN7|1of3
27,A0A7X3FKZ4,3,11354.0,23958.0,0.0,A0A7X3FKZ4|1of3,A0A7X3FKZ4,A0A7X3FKZ4|1of3
36,A0A4P9VNH1,3,7789.0,15598.0,0.0,A0A4P9VNH1|1of3,A0A4P9VNH1,A0A4P9VNH1|1of3
...,...,...,...,...,...,...,...,...
41181,A0A2Z2NGA0,1,32063.0,11290.0,3.0,A0A2Z2NGA0|1of1,A0A2Z2NGA0,A0A2Z2NGA0|1of1
41182,A0A3N6MAZ1,1,37246.0,13989.0,34.0,A0A3N6MAZ1|1of1,A0A3N6MAZ1,A0A3N6MAZ1|1of1
41183,A0A8T3UZL4,1,37791.0,26228.0,65.0,A0A8T3UZL4|1of1,A0A8T3UZL4,A0A8T3UZL4|1of1
41184,M0IGJ5,1,32403.0,36785.0,3.0,M0IGJ5|1of1,M0IGJ5,M0IGJ5|1of1
41185,R4W8T7,1,32624.0,37540.0,3.0,R4W8T7|1of1,R4W8T7,R4W8T7|1of1

In [22]:
import numpy as np
import pandas as pd

SEQ_ID = "Uniprot_Accessions"          # assumed: one row == one sequence
DOMCOL = "Total_domains"    # assumed: TOTAL no. of GH18 domains in that sequence
df = annot_cluster162.copy()
d = df.drop_duplicates(subset=SEQ_ID).copy()
d[DOMCOL] = pd.to_numeric(d[DOMCOL], errors="coerce")

# cluster size = no. of sequences per cluster
d["cluster_size"] = d.groupby("cluster")[SEQ_ID].transform("size")

bins   = [0, 1, 2, 4, 9, 19, 49, 99, 499, np.inf]
labels = ["1", "2", "3–4", "5–9", "10–19", "20–49", "50–99", "100–499", "500+"]
d["size_bin"] = pd.cut(d["cluster_size"], bins=bins, labels=labels)

g = d.groupby("size_bin", observed=False)
stats = pd.DataFrame({
    "n_clusters": g["cluster"].nunique(),
    "n_seqs":     g.size(),
    "one_n":      g[DOMCOL].agg(lambda s: (s == 1).sum()),
    "three_n":    g[DOMCOL].agg(lambda s: (s == 3).sum()),
})
stats.loc["Total"] = stats.sum()

stats["one_pct"]   = 100 * stats["one_n"]   / stats["n_seqs"]
stats["three_pct"] = 100 * stats["three_n"] / stats["n_seqs"]

supp8 = pd.DataFrame({
    "Cluster-size bin":   stats.index,
    "No. of clusters":    stats["n_clusters"].map("{:,.0f}".format).values,
    "Total sequences":    stats["n_seqs"].map("{:,.0f}".format).values,
    "One-domain, n (%)":  [f"{n:,.0f} ({p:.1f}%)" for n, p in zip(stats["one_n"], stats["one_pct"])],
    "Three-domain, n (%)":[f"{n:,.0f} ({p:.1f}%)" for n, p in zip(stats["three_n"], stats["three_pct"])],
})

# --- sanity checks: read these before using the table ---
print("rows:", len(df), "| unique", SEQ_ID + ":", df[SEQ_ID].nunique())
print("NaN Domain_number:", d[DOMCOL].isna().sum())
print("Domain_number value counts:\n", d[DOMCOL].value_counts(dropna=False).sort_index())
# does the 'NofM' suffix agree with Domain_number? (i.e. is Domain_number a total, not an index?)
m = d[SEQ_ID].str.extract(r"(\d+)of(\d+)$").astype(float)
print("suffix M == Domain_number:", (m[1] == d[DOMCOL]).mean(),
      "| suffix N == Domain_number:", (m[0] == d[DOMCOL]).mean())

display(supp8)
supp8#.to_csv("supplementary_table_8.csv", index=False)

rows: 39574 | unique Uniprot_Accessions: 37705
NaN Domain_number: 0
Domain_number value counts:
 Total_domains
1    37015
2      652
3       36
4        3
Name: count, dtype: int64
suffix M == Domain_number: 0.0 | suffix N == Domain_number: 0.0

,Cluster-size bin,No. of clusters,Total sequences,"One-domain, n (%)","Three-domain, n (%)"
0,1,132,132,130 (98.5%),0 (0.0%)
1,2,34,68,66 (97.1%),0 (0.0%)
2,3–4,31,102,92 (90.2%),0 (0.0%)
3,5–9,19,116,106 (91.4%),0 (0.0%)
4,10–19,14,202,187 (92.6%),0 (0.0%)
5,20–49,20,673,648 (96.3%),0 (0.0%)
6,50–99,8,520,510 (98.1%),0 (0.0%)
7,100–499,8,"1,482","1,327 (89.5%)",0 (0.0%)
8,500+,5,"34,410","33,948 (98.7%)",36 (0.1%)
9,Total,271,"37,705","37,014 (98.2%)",36 (0.1%)

,Cluster-size bin,No. of clusters,Total sequences,"One-domain, n (%)","Three-domain, n (%)"
0,1,132,132,130 (98.5%),0 (0.0%)
1,2,34,68,66 (97.1%),0 (0.0%)
2,3–4,31,102,92 (90.2%),0 (0.0%)
3,5–9,19,116,106 (91.4%),0 (0.0%)
4,10–19,14,202,187 (92.6%),0 (0.0%)
5,20–49,20,673,648 (96.3%),0 (0.0%)
6,50–99,8,520,510 (98.1%),0 (0.0%)
7,100–499,8,"1,482","1,327 (89.5%)",0 (0.0%)
8,500+,5,"34,410","33,948 (98.7%)",36 (0.1%)
9,Total,271,"37,705","37,014 (98.2%)",36 (0.1%)